### ISSUE TITLE
Updating versions

### ISSUE THREAD

**Issue by nightscape** [machielg/sparkle-hypothesis#2]
Hi @machielg, thanks for merging my PR so quickly!
I'm just trying out sparkle-hypothesis for the first time, and I'd have two questions:

1. Even though the latest Github release and `build.py` show version 1.0.2 as the latest version, there's [version 1.3.1 on Pypi](https://pypi.org/project/sparkle-hypothesis/), so I'm wondering where this version is coming from?
2. If my first experiments with sparkle-hypothesis are successful, I'd probably try to upgrade dependencies to their latest versions. Would it be ok to create a few follow-up PRs?

**Comment by machielg** [comment]
the dependencies have been upgraded and the latest version is now on (tagged) on github and pypi. Any contributions or ideas are welcome!
